version: '3.8'

services:
  app:
    build: .
    ports:
      - "7070:7070"
    environment:
      - SERVER_PORT
      - BASE_URL
      - BASE_GET_URL
      - DATABASE_URL=postgres://postgres:password@localhost:5433/tgbot?sslmode=disable
      - LOG_LEVEL=development
    depends_on:
      - db

  db:
    image: postgres:14
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tgbot
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

volumes:
  db-data: